version: '3.4'

services:
    apiproject:
     build:
      context: .
      dockerfile: APIProject/Dockerfile
     ports:
      - "8880:80"
      - "8443:443"
     environment:
      APSNETCORE_URLS: "https://+;http://+"
      APSNETCORE_HTTPS_PORT: "8443"
      ASPNETCORE_ENVIRONMENT: "Development"
     volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.apsnet/https/